import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Login from '@/components/Login/index'
import Register from '@/components/Register/index'
import Download from '@/components/Download/index'

import Footer from '@/components/Footer/index'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Instagram Login Layout</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.main_container}>
          <Login></Login>
          <Register></Register>
          <Download></Download>
        </div>
      </main>
      <Footer></Footer>
    </>
  )
}
